[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
contract = "9S7z9xojyDARK3kqaDRhcabHA4sWERWMmQ31DbB9uVde"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/0xanmol/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
